Hw_01
vlykhvar/concurrency pull request #1
Opened 2021-02-22 11:07 UTC by vlykhvar

2021-02-22 11:42 UTC, YuraBondarenko requested changes

2021-02-22 11:42 UTC, YuraBondarenko commented on src/com/company/Main.java
> +        Thread second = new Thread(new Runnables());
make methods in class Counter not static and pass `counter` into constructor

2021-02-22 11:56 UTC, YuraBondarenko approved these changes

2021-02-22 15:45 UTC, RomanDubovskyi requested changes

2021-02-22 15:45 UTC, RomanDubovskyi commented on src/com/company/Counter.java
> +            this.count += count;
it looks like regular setter but has unprodictable logic, let's fix it 
(if you want to have method that increments your count value create a separate one)

2021-02-22 15:45 UTC, RomanDubovskyi commented on src/com/company/Runnables.java
> +            counter.setCount(1);
?

2021-02-22 15:45 UTC, RomanDubovskyi commented on src/logging
> +Thread-0: counter is 200
empty line at the end of the file

2021-02-22 16:53 UTC, vlykhvar commented on src/com/company/Runnables.java
> +            counter.setCount(1);
chenged to logic name

2021-02-23 09:16 UTC, RomanDubovskyi approved these changes

2021-02-23 09:16 UTC, RomanDubovskyi commented on src/com/company/Counter.java
> +        return count;
```suggestion
    public int increment() {
         return ++count;
```

2021-02-23 09:16 UTC, RomanDubovskyi commented on src/com/company/Threads.java
> +    public final Counter counter;
```suggestion
    private final Counter counter;
```
we don't need it to be public

2021-02-23 09:29 UTC, merged