all done
vlykhvar/concurrency pull request #2
Opened 2021-02-24 09:00 UTC by vlykhvar

2021-02-24 10:04 UTC, gigbat requested changes
Where is your implementation of the callable interface?

2021-02-24 10:05 UTC, vlykhvar commented on src/com/company/hw2/Join.java
> +    public int execure() {
changed

2021-02-24 10:46 UTC, gigbat approved these changes

2021-02-24 12:12 UTC, Sofasmile requested changes

2021-02-24 12:12 UTC, Sofasmile commented on src/com/company/hw2/TaskTest.java
> +    private static Join join;
функціонал двох різних класів ми сетсуємо в двох різних класах

2021-02-24 12:12 UTC, Sofasmile commented on src/com/company/hw2/TaskTest.java
> +        join = new Join(list);
не очевидно, чому ми тут присвоюємо пусті списки в об'єкти класів. Спочатку потрібно їх проініціалізувати

2021-02-24 12:12 UTC, Sofasmile commented on src/com/company/hw2/TaskTest.java
> +    public void setList(int number) {
назва методу не зовсім очевидна. Пропоную рандомно генерувати числа для заповнення ліста.

2021-02-24 12:12 UTC, Sofasmile commented on src/com/company/hw2/TaskTest.java
> +    public void getSumJoin_ok() throws Exception {
прокидати в тестах Exception не зовсім ок

2021-02-24 12:12 UTC, Sofasmile commented on src/com/company/hw2/Join.java
> +public class Join implements Callable<Integer> {
краще розділити логіку. Зробити окремо клас, який буде імплементити Callable і в методі call буде лише рахуватись сума елементів в списку, а також зробити ще один клас де уже буде відбуватись робота з ExecutorService

2021-02-24 12:12 UTC, Sofasmile commented on src/com/company/hw2/Join.java
> +        return ForkJoinTask.invokeAll(list).stream().map(ForkJoinTask::join).mapToInt(i -> i).sum();
ForkJoinTask відноситься до RecursiveTask,  а з Callable повинен працювати ExecutorService

2021-02-24 15:05 UTC, Sofasmile requested changes

2021-02-24 15:05 UTC, Sofasmile commented on src/com/company/hw2/CallableCustomTest.java
> +        setUp();
викликати щоразу метод setUp() виглядає дуже дивно...
можна як варіант розбити всі перевірку по окремих методах, і тоді setUp() автоматично буде відпрацьовувати перед кожним з них

2021-02-24 15:05 UTC, Sofasmile commented on src/com/company/hw2/CallableCustomTest.java
> +        callableCustom = new CallableCustom(createList.createList(1));
ми повинні тестити не callableCustom, а на його основі створити ExecutorService і тестити його роботу
тут є щось наподобі того що треба зробити. Можеш погуглити в напрямку "ExecutorService with Callable examples"

2021-02-25 14:51 UTC, Sofasmile approved these changes

2021-02-25 14:51 UTC, Sofasmile commented on src/test/com/company/hw2/CallableCustomTest.java
> +    ExecutorServiceCustom executor;
не забуваємо про модифікатор доступу

2021-02-25 15:00 UTC, merged